### ISSUE TITLE
Filename too long while sourcing + transforming nodes

### ISSUE THREAD

**Issue by Ameobea** [leolabs/gatsby-source-spotify#6]
```
"gatsby-source-spotify" threw an error while running the sourceNodes lifecycle:

failed to process https://mosaic.scdn.co/640/11497fc4b5d38edf66e17c37bc82e85a60e98b2f2ee455259ee078b07d9d80385bc3368d26a76d889c5955308ce2843b6879091e8e1fda9df8b15413e67136d00b23acc1b57414c419c47755a9a8280b
Error: ENAMETOOLONG: name too long, rename '/home/casey/homepage/.cache/gatsby-source-filesystem/tmp-871f83b51c76c1f514db0268ca6c5783' -> '/home/casey/homepage/.cache/gatsby-source-filesystem/871f83b51c76c1f514db0268ca6c5783/11497fc4b5d38edf66e17c37bc82e85a60e98b2f2ee455259ee078b07d9d80385bc3368d26a76d889c5955308ce2843b6879091e8e1fda9df8b15413e67136d00b23acc1b57414c419c47755a9a8280b.jpg'

⠼ source and transform nodes
```

It looks like it's pulling down some "mosaic" image (https://mosaic.scdn.co/640/11497fc4b5d38edf66e17c37bc82e85a60e98b2f2ee455259ee078b07d9d80385bc3368d26a76d889c5955308ce2843b6879091e8e1fda9df8b15413e67136d00b23acc1b57414c419c47755a9a8280b) which combines the album art and, I assume, the IDs of each of the four underlying images.

Is there some way to disable the sourcing of these mosaic images, or just skip over files that are too long?

**Comment by leolabs** [comment]
Hey @Ameobea,
thanks for filing the issue and for creating a PR!

I've decided to fix the root cause of the problem by making sure file names don't exceed the allowed length rather than ignoring files whose name is too large like you proposed in your PR. This will make sure that every image is available in Gatsby as long as it can be downloaded from Spotify's CDN.

Please tell me if this fix works for you :)

**Comment by Ameobea** [comment]
@leolabs your solution looks great - tyvm for the quick fix (and for the awesome library)!

**Comment by leolabs** [comment]
Awesome! I'm happy I could help :)
